export const APP_ROUTES = {
  login: '/login',
  users: '/admin/users',
  userCompare: '/admin/users/compare',
  userProfile: (userId = ':id') => `/admin/users/${userId}/profile`,
  userManagement: '/admin/user-management',
  commerce: '/admin/commerce',
  catalog: '/admin/catalog',
  inventory: '/admin/inventory',
  categories: '/admin/categories',
  subcategories: '/admin/subcategories',
  products: '/admin/products',
  productBundles: '/admin/product-bundles',
  requisitions: '/admin/operations/requisitions',
  procurements: '/admin/operations/procurements',
  stockReceipts: '/admin/operations/stock-receipts',
  productStocks: '/admin/operations/product-stocks',
  inventoryAdjustments: '/admin/operations/inventory-adjustments',
  orders: '/admin/orders',
  transactions: '/admin/transactions',
  coupons: '/admin/coupons',
  companyAccounts: '/admin/company-accounts',
}
