import { MessageSquare, Printer } from 'lucide-react'
import CommonDrawer from '../../../components/ui/CommonDrawer'

const date = (value) => value ? new Date(value).toLocaleDateString() : '—'
const money = (value) => `৳${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const escapeHtml = (value) => String(value ?? '—').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character])

export default function RequisitionDetailDrawer({ record, onClose }) {
  const items = record.items || []
  const total = items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unit_cost || 0), 0)
  const units = items.reduce((sum, item) => sum + Number(item.quantity || 0), 0)
  const printInvoice = () => {
    const popup = window.open('', '_blank', 'width=900,height=700')
    if (!popup) return
    const rows = items.map((item) => `<tr><td>${escapeHtml(item.product_name)}</td><td>${escapeHtml(item.sku)}</td><td>${item.quantity}</td><td>${item.quantity_received}</td><td>${money(item.unit_cost)}</td><td>${money(Number(item.quantity || 0) * Number(item.unit_cost || 0))}</td></tr>`).join('')
    popup.document.write(`<!doctype html><html><head><title>${escapeHtml(record.requisition_number)} invoice</title><style>body{font:14px Arial;color:#172033;padding:32px}header{display:flex;justify-content:space-between;border-bottom:2px solid #2563eb;padding-bottom:18px}h1{margin:0;font-size:24px}small{color:#64748b}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}.card{padding:12px;border:1px solid #cbd5e1;border-radius:6px}.label{display:block;color:#64748b;font-size:11px;text-transform:uppercase}table{width:100%;border-collapse:collapse}th,td{padding:10px;border:1px solid #cbd5e1;text-align:left}th{background:#eff6ff}tfoot td{font-weight:700}</style></head><body><header><div><small>REQUISITION INVOICE</small><h1>${escapeHtml(record.requisition_number)}</h1><small>${escapeHtml(record.procurement_number || 'No procurement created')}</small></div><div><strong>${escapeHtml(record.status)}</strong><br><small>${escapeHtml(date(record.created_at))}</small></div></header><div class="grid"><div class="card"><span class="label">Requested by</span>${escapeHtml(record.requested_by)}<br><small>${escapeHtml(record.department)}</small></div><div class="card"><span class="label">Supplier</span>${escapeHtml(record.supplier_name)}<br><small>${escapeHtml(record.reference_no)}</small></div><div class="card"><span class="label">Required by</span>${escapeHtml(date(record.required_by))}<br><small>Priority: ${escapeHtml(record.priority)}</small></div></div><table><thead><tr><th>Product</th><th>SKU</th><th>Requested</th><th>Received</th><th>Unit cost</th><th>Line total</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><td colspan="2">Total</td><td>${units}</td><td></td><td></td><td>${money(total)}</td></tr></tfoot></table>${record.notes ? `<p><strong>Notes:</strong> ${escapeHtml(record.notes)}</p>` : ''}</body></html>`)
    popup.document.close(); popup.focus(); window.setTimeout(() => popup.print(), 250)
  }
  const sendSms = () => { window.location.href = `sms:?&body=${encodeURIComponent(`Requisition ${record.requisition_number}: ${units} units, total ${money(total)}. Status: ${record.procurement_status || record.status}.`)}` }
  return <CommonDrawer title="Requisition invoice" subtitle={`${record.requisition_number}${record.procurement_number ? ` · ${record.procurement_number}` : ''}`} onClose={onClose}><article className="requisition-invoice"><header className="requisition-invoice__header"><div><span>REQUISITION INVOICE</span><h3>{record.requisition_number}</h3><p>{record.procurement_number || 'Procurement not created yet'}</p></div><div className="requisition-invoice__actions"><button type="button" className="routes-control" onClick={printInvoice}><Printer size={14} />Print</button><button type="button" className="routes-control routes-control--blue" onClick={sendSms}><MessageSquare size={14} />SMS</button></div></header><section className="requisition-invoice__parties"><div><span>Requested by</span><strong>{record.requested_by || '—'}</strong><small>{record.department || 'No department'}</small></div><div><span>Supplier</span><strong>{record.supplier_name || 'Not specified'}</strong><small>Ref: {record.reference_no || '—'}</small></div><div><span>Request details</span><strong>{date(record.created_at)}</strong><small>Required by: {date(record.required_by)}</small></div></section><section className="requisition-invoice__meta"><div><span>Status</span><strong>{record.procurement_status || record.status || 'pending'}</strong></div><div><span>Priority</span><strong>{record.priority || 'normal'}</strong></div><div><span>Approved by</span><strong>{record.approved_by_name || '—'}</strong></div><div><span>Received by</span><strong>{record.received_by_name || '—'}</strong></div></section>{record.notes ? <p className="requisition-detail-notes"><strong>Notes:</strong> {record.notes}</p> : null}<section className="stock-history"><h3>Requested items</h3><div className="stock-history__table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Requested</th><th>Received</th><th>Unit cost</th><th>Line total</th></tr></thead><tbody>{items.map((item) => <tr key={item.requisition_product_id}><td>{item.product_name}</td><td>{item.sku || '—'}</td><td>{item.quantity}</td><td>{item.quantity_received}</td><td>{money(item.unit_cost)}</td><td>{money(Number(item.quantity || 0) * Number(item.unit_cost || 0))}</td></tr>)}</tbody><tfoot><tr><td colSpan="2">Total</td><td>{units}</td><td></td><td></td><td>{money(total)}</td></tr></tfoot></table></div></section></article></CommonDrawer>
}
